### ISSUE TITLE
No node app.js after done the compiling step.

### ISSUE THREAD

**Issue by An020** [HumanDuck23/virtual-hypixel-v4#13]
After completing step 9, i got AbortSingnal error and looked up in Github issues page
And somone said its fine and they said i can safely ignore it and move on step 10 and use the app as normal
But theres no node app.js.

[ Im new to node and typescript so if this is a stupid issue, im very sorry]
![image](https://user-images.githubusercontent.com/88565171/188253065-0a8a1a9d-787c-4302-87ec-677d6998817d.png)

**Comment by JosTheDude** [comment]
Hey! Thanks for using Virtual Hypixel v4!

What step 9 means is that you should run `node app.js` in your terminal, not as a file.

Make sure, in order to run said file, that your current directory within the terminal is also in the `src` folder which will display as `parent-directory\whateveryounamedvirtualhypixel\(input blah blah directory listing here)\src` in your terminal (attached images for reference)
![image](https://user-images.githubusercontent.com/43651265/188254854-34d20832-84f6-4e4c-a386-155eb5dccac6.png)

**Comment by An020** [comment]
Thanks for answering my issue, i was stupid enough for not knowing its a command
Thanks :).
