### ISSUE TITLE
Bedwars Stat Checkers DNW

### ISSUE THREAD

**Issue by JosTheDude** [HumanDuck23/virtual-hypixel-v4#2]
No idea if it pulls stats, but it doesn't send any chat messages regarding the stats of the player in the game or joining players in bedwars.

(still works in bw)

**Comment by HumanDuck23** [comment]
Bedwars and similar modes were temporarily removed in commit [280e9d8](https://github.com/HumanDuck23/virtual-hypixel-v4/commit/280e9d85cd52a1bc21db5a1f775f7ff5f45ce898) due to some problems with how it was done, currently only duels works. Will fix later.

EDIT: Should be fixed in commit [9565a58](https://github.com/HumanDuck23/virtual-hypixel-v4/commit/9565a585cd3a9c94c8faa205ffc0fac029972425). The reason I removed it is because I was only listening for `named_entity_spawn` packets, but those also get sent in game so the chat was constantly being filled with stats messages. Now the module should be making sure the game hasn't started yet before sending the stats (I haven't tested that yet, pretty sure it should work though, will test in a couple hours)
